USE [MexiaSource]
GO

/****** Object:  Table [dbo].[SC_Area]    Script Date: 2018-01-31 5:51:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SC_Area](
	[SC_AreaID] [smallint] NOT NULL,
	[SC_AreaName] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_SC_Area_SC_AreaID] PRIMARY KEY CLUSTERED 
(
	[SC_AreaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

